### ISSUE TITLE
Обновить расписание PM4

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/bfubot#9]
Я получил такое письмо:

"
Уважаемые преподаватели!
С сегодняшнего дня аудитории 210-211 нет! Все ваши пары перенесены в аудиторию 230А (вход через 230 ауд.)
"

Прошу изменить расписание /pm4 все аудитории 210-211 на 230А

**Comment by Waaaaaaaake** [comment]
Моя задача
